model_type: "regressor" # can be either a classifier or a regressor
data_mode: "full" # can be full or random 
flux: "efiitg_gb" 

data:
  train: "/share/rcifdata/tmadula/data/UKAEA/train_data_clipped.pkl"
  validation: "/share/rcifdata/tmadula/data/UKAEA/valid_data_clipped.pkl"
  test: "/share/rcifdata/tmadula/data/UKAEA/test_data_clipped.pkl"
save_paths: 
  models: /share/rcifdata/tmadula/data/UKAEA/baselines/regressors
  losses: /share/rcifdata/tmadula/data/UKAEA/baselines/regressors

hyperparameters:
  rand_sample_size: 20_000
  epochs: 200
  patience: 50
  train_batch_size: 4096
  valid_batch_size: 4096
