CL_method: shrink_perturb
common:
  MC_dropout_runs: 50
  Nbootstraps: 10
  acquisition: individual
  flux:
  - efiitg_gb
  hyperparams:
    batch_size: 256
    buffer_size: 500
    candidate_size: 10000
    dropout: 0.1
    lambda: 1
    model_size: deep
    test_size: 10000
    train_size: 20000
    valid_size: 10000
  initial_epochs: 30
  iterations: 10
  keep_prob: 0.25
  learning_rate: 0.001
  logging_level: DEBUG
  patience: 10
  retrain_classifier: true
  retrain_regressor: true
  sample_size_debug: 1
  train_epochs: 30
  train_patience: 10
lambda_task: 1
mem_replay: 2
task1:
  data:
    test: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Lmode/test_data_clipped.pkl
    train: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Lmode/train_data_clipped.pkl
    validation: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Lmode/valid_data_clipped.pkl
  pretrained:
    Classifier:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/carbonwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/carbonwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/carbonwall/shrink_perturb/ITGclassifier.pt
        trained: false
    Regressor:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/carbonwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/carbonwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/carbonwall/shrink_perturb/ITGregressor.pt
        trained: false
  save_paths:
    outputs: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/outputs/CL/carbonwall/shrink_perturb/
    plots: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/plots/CL/carbonwall/shrink_perturb/
task2:
  data:
    test: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Hmode/test_data_clipped.pkl
    train: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Hmode/train_data_clipped.pkl
    validation: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/carbonwall/Hmode/valid_data_clipped.pkl
  pretrained:
    Classifier:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGclassifier.pt
        trained: false
    Regressor:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGregressor.pt
        trained: false
  save_paths:
    outputs: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/outputs/CL/berilliumwall/shrink_perturb/
    plots: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/plots/CL/berilliumwall/shrink_perturb/
task3:
  data:
    test: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Lmode/test_data_clipped.pkl
    train: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Lmode/train_data_clipped.pkl
    validation: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Lmode/valid_data_clipped.pkl
  pretrained:
    Classifier:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGclassifier.pt
        trained: false
    Regressor:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGregressor.pt
        trained: false
  save_paths:
    outputs: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/outputs/CL/berilliumwall/shrink_perturb/
    plots: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/plots/CL/berilliumwall/shrink_perturb/
task4:
  data:
    test: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Hmode/test_data_clipped.pkl
    train: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Hmode/train_data_clipped.pkl
    validation: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/data/berilliumwall/Hmode/valid_data_clipped.pkl
  pretrained:
    Classifier:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGclassifier.pt
        trained: false
    Regressor:
      efeetg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/ETGclassifier.pt
        trained: false
      efetem_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/TEMclassifier.pt
        trained: false
      efiitg_gb:
        save_path: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/saved/CL/berilliumwall/shrink_perturb/ITGregressor.pt
        trained: false
  save_paths:
    outputs: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/outputs/CL/berilliumwall/shrink_perturb/
    plots: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/UKAEAGroupProject/plots/CL/berilliumwall/shrink_perturb/
